services:
  server-api:
    build: ./server-api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on: 
      - postgres-db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/data
  postgres-db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - .:/database