services:
  server-api:
    build: ./server-api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/data
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - .:/database
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=lauti
      - POSTGRES_DB=products